// Generated by CIRCT firtool-1.62.1
module CounterModule(
  input        clock,
               reset,
  output [6:0] io_second,
               io_minutes,
               io_hour,
  input        io_enable,
               io_reset,
  output [6:0] io_led_second1,
               io_led_second2,
               io_led_minutes1,
               io_led_minutes2,
               io_led_hour1,
               io_led_hour2
);

  wire [15:0][6:0] _GEN =
    '{7'h7F,
      7'h7F,
      7'h7F,
      7'h7F,
      7'h7F,
      7'h7F,
      7'h4,
      7'h0,
      7'hF,
      7'h60,
      7'h24,
      7'h4C,
      7'h6,
      7'h12,
      7'h4F,
      7'h1};
  reg  [6:0]       secondsReg;
  reg  [6:0]       minutesReg;
  reg  [6:0]       hoursReg;
  reg  [31:0]      tick;
  wire [6:0]       secOnes = secondsReg % 7'hA;
  wire [6:0]       secTens = secondsReg / 7'hA;
  wire [6:0]       minOnes = minutesReg % 7'hA;
  wire [6:0]       minTens = minutesReg / 7'hA;
  wire [6:0]       hourOnes = hoursReg % 7'hA;
  wire [6:0]       hourTens = hoursReg / 7'hA;
  always @(posedge clock) begin
    if (reset) begin
      secondsReg <= 7'h0;
      minutesReg <= 7'h0;
      hoursReg <= 7'h0;
      tick <= 32'h0;
    end
    else if (tick == 32'h1F4) begin
      automatic logic _hoursReg_T = secondsReg == 7'h3B;
      if (secondsReg < 7'h3B)
        secondsReg <= secondsReg + 7'h1;
      else
        secondsReg <= 7'h0;
      if (_hoursReg_T) begin
        if (minutesReg < 7'h3B)
          minutesReg <= minutesReg + 7'h1;
        else
          minutesReg <= 7'h0;
      end
      if (_hoursReg_T & minutesReg == 7'h3B) begin
        if (hoursReg < 7'h17)
          hoursReg <= hoursReg + 7'h1;
        else
          hoursReg <= 7'h0;
      end
      tick <= 32'h0;
    end
    else begin
      if (io_reset) begin
        secondsReg <= 7'h0;
        minutesReg <= 7'h0;
        hoursReg <= 7'h0;
      end
      if (io_reset | ~io_enable) begin
      end
      else
        tick <= tick + 32'h1;
    end
  end // always @(posedge)
  assign io_second = secondsReg;
  assign io_minutes = minutesReg;
  assign io_hour = hoursReg;
  assign io_led_second1 = _GEN[secOnes[3:0]];
  assign io_led_second2 =
    secTens == 7'h0
      ? 7'h1
      : secTens == 7'h1
          ? 7'h4F
          : secTens == 7'h2
              ? 7'h12
              : secTens == 7'h3
                  ? 7'h6
                  : secTens == 7'h4
                      ? 7'h4C
                      : secTens == 7'h5
                          ? 7'h24
                          : secTens == 7'h6
                              ? 7'h60
                              : secTens == 7'h7
                                  ? 7'hF
                                  : secTens == 7'h8
                                      ? 7'h0
                                      : secTens == 7'h9 ? 7'h4 : 7'h7F;
  assign io_led_minutes1 = _GEN[minOnes[3:0]];
  assign io_led_minutes2 =
    minTens == 7'h0
      ? 7'h1
      : minTens == 7'h1
          ? 7'h4F
          : minTens == 7'h2
              ? 7'h12
              : minTens == 7'h3
                  ? 7'h6
                  : minTens == 7'h4
                      ? 7'h4C
                      : minTens == 7'h5
                          ? 7'h24
                          : minTens == 7'h6
                              ? 7'h60
                              : minTens == 7'h7
                                  ? 7'hF
                                  : minTens == 7'h8
                                      ? 7'h0
                                      : minTens == 7'h9 ? 7'h4 : 7'h7F;
  assign io_led_hour1 = _GEN[hourOnes[3:0]];
  assign io_led_hour2 =
    hourTens == 7'h0
      ? 7'h1
      : hourTens == 7'h1
          ? 7'h4F
          : hourTens == 7'h2
              ? 7'h12
              : hourTens == 7'h3
                  ? 7'h6
                  : hourTens == 7'h4
                      ? 7'h4C
                      : hourTens == 7'h5
                          ? 7'h24
                          : hourTens == 7'h6
                              ? 7'h60
                              : hourTens == 7'h7
                                  ? 7'hF
                                  : hourTens == 7'h8
                                      ? 7'h0
                                      : hourTens == 7'h9 ? 7'h4 : 7'h7F;
endmodule

